### ISSUE TITLE
下载 Telegram 受保护的媒体资源 | 失效了

### ISSUE THREAD

**Issue by crazypeace** [makeding/blog#1]
大佬好!

博客没有评论留言系统, 所以我找到这里留言来了. 抱歉打扰了!

之前 大佬 的方案是有效的.

刚刚我想再用. 发现:
1. a版不能播放受保护的视频. 提示要使用桌面APP.
2. k版能播放, 但是大佬的脚本失效了, 不能显示下载按钮

我自己的JS水平不够, 看了大佬的博文, 无法找到解决问题的方法.

希望大佬更新一下脚本, 或者有更详细的解决方案的描述, 可以让我自己动手解决问题.

我下载受保护的视频的需求不是很经常, 可以接受一次性的, 稍微麻烦一点的操作方案.

**Comment by makeding** [comment]
1. a 版我这下载正常（右键或者右上角均显示下载按钮）。然后如果播放浏览器放不了的格式就会提示到 app 内观看。
所以我觉得你右键可以 download
<img width="214" alt="image" src="https://github.com/user-attachments/assets/0ca5357e-0c5b-47de-8522-94cf874b2391">

2. k 版好像有一点坏了我看看怎么修，目前观察到的情况是，如果在群组里关联的频道好像是不能下载的。


至于其他方案的话，我这没有。
你可以尝试第三方 Telegram 比如说 https://github.com/TDesktop-x64/tdesktop
但正如我文章所说，有可能的炸号风险。

**Comment by crazypeace** [comment]
感谢大佬回应, 我再试试.
第三方解开限制的客户端 我肯定是不敢用 风险太高.
